# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sbot < Formula
  desc ""
  homepage ""
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yteraoka/sbot/releases/download/v0.0.6/sbot_0.0.6_darwin_amd64.tar.gz"
      sha256 "623e6a4b4e926b9f1fd1f4325cbddc1461818902ab2f2d767cd1cba3ae062fc1"

      define_method(:install) do
        bin.install "sbot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yteraoka/sbot/releases/download/v0.0.6/sbot_0.0.6_darwin_arm64.tar.gz"
      sha256 "1e2ea616f9831c3f594220a4453efb03800fbd1f3dfd82d5153bfbedb667ffa0"

      define_method(:install) do
        bin.install "sbot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yteraoka/sbot/releases/download/v0.0.6/sbot_0.0.6_linux_amd64.tar.gz"
      sha256 "82a51c391b63f7286341d5b7875aea85babb49faf1d4025b634fe5c3b683b6f0"
      define_method(:install) do
        bin.install "sbot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yteraoka/sbot/releases/download/v0.0.6/sbot_0.0.6_linux_arm64.tar.gz"
      sha256 "a5eef3508082b20df6f3352c421685f544393c69aaa5ec4585d8f5e60e83320e"
      define_method(:install) do
        bin.install "sbot"
      end
    end
  end
end
