# This file was generated by GoReleaser. DO NOT EDIT.
cask "athq" do
  version "1.3.0"

  on_macos do
    on_arm do
      sha256 "85ec371cab8d0922e58d123ce6a8521f3eaa4aedca4c7a9fe6622041a80e3260"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3dd10074308de14bd2830dd77335ad9baac9dfd3eef5292b0a7232aaf4deaebb"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d98e2903fcdaf3d9a0b46d28917500907497cdfe26920fb4448ee888cebe81b1"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "627f4ff792b0a93cdb3ee39dd77c78e92bdd59a154bea248735dbfc2c2cedfa3"
      url "https://github.com/yteraoka/athq/releases/download/v#{version}/athq_#{version}_linux_amd64.tar.gz"
    end
  end

  name "athq"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "athq"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/athq"]
    end
  end

  # No zap stanza required
end
