# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "2.1.0"

  on_macos do
    on_arm do
      sha256 "fa2b055d0216244f9802ae1f5dbd9a2d8e333a1ea085b5f07f5f78364d146065"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e837c737ed8256b506febdf63c7e000fad01c55eca8f8b2046629ad0b38467fb"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e94fd9cf593f65ee99d55dc4d11b4cceed4e983c32ab9ee1b2818be234a4d25e"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cc803334420cd50b7bcc594a4cf6f3fabd3221c3a02825bb4138563b051b2dbf"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccr"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
  end

  # No zap stanza required
end
