# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "3.0.0"

  on_macos do
    on_arm do
      sha256 "6e596df432f2a9355c13853a5fdf697e9f8a7b4934629606138a848654304514"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4c57a1df75d3c13331885d055aacf69827ff58522a51233194e0ddd1e5f1eb01"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f63f2ee937b8f78c03a2026b7313ae5b1d165cff56a2ea2d622f3917fcffcdb6"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "182d8ddfbb1c5e50ebe6c7f195bdf2b9764443404873226956d37f0a6d03928d"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccr"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
  end

  # No zap stanza required
end
