# This file was generated by GoReleaser. DO NOT EDIT.
cask "ccr" do
  version "2.3.0"

  on_macos do
    on_arm do
      sha256 "9ed46d1e1a5d5a67656084aa18076b714e1a43cb3e7595225043c5fc443bc145"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a88e4dee4145c46c27d713d604e8fd61fc82b77e8784bcb5f0fce8dd2e5e1b2b"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "041c5f1f863124f812cff2795c5c4268c966349adfa23d30f4ae49692f2d84e9"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2b6c26763e9ea0a07f873dafad27e7f73b3216a207d58f94b73f05eacff714f9"
      url "https://github.com/yteraoka/ccr/releases/download/v#{version}/ccr_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ccr"
  desc ""
  homepage ""

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ccr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ccr"]
    end
  end

  # No zap stanza required
end
