# This file was generated by GoReleaser. DO NOT EDIT.
cask "httc" do
  name "httc"
  desc ""
  homepage ""
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httc"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_darwin_amd64.tar.gz"
      sha256 "52a545831733dab36e91f361ddfcd193e3b30270447286f00ff1a3eff787d269"
    end
    on_arm do
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_darwin_arm64.tar.gz"
      sha256 "e10bd6c27812accd3d5088bb70fbd6fe814214c5677e6ecb451b4f0b74152d9a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_linux_amd64.tar.gz"
      sha256 "2a0da943d72914ce3d14749c595e615b27d5b7ba7756d83d4b4ac6cfdb177a73"
    end
    on_arm do
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_linux_arm64.tar.gz"
      sha256 "5627c1b386645ee4b2c6225b2cf4888231d35b8c68017daa2a3d3e012f11e3e1"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/httc"]
    end
  end

  # No zap stanza required
end
