# This file was generated by GoReleaser. DO NOT EDIT.
cask "httc" do
  name "httc"
  desc ""
  homepage ""
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "httc"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_darwin_amd64.tar.gz"
      sha256 "6f348e99862dadde12fcb861d921725ab77179751b0bf456693b1f9c3ed04397"
    end
    on_arm do
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_darwin_arm64.tar.gz"
      sha256 "660811eaa0a6af3042b685e42926d5b119bb28e06285ac2bdb02e966ff126d29"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_linux_amd64.tar.gz"
      sha256 "263fd445d85d825933fe04d1dd8d09c6bc157574b693d52a2d7292eddfe69068"
    end
    on_arm do
      url "https://github.com/yteraoka/httc/releases/download/v#{version}/httc_#{version}_linux_arm64.tar.gz"
      sha256 "5c68b8217ef74018abac42c89883a19579f005e64232324843934048e30bcb7c"
    end
  end

  # No zap stanza required
end
