# This file was generated by GoReleaser. DO NOT EDIT.
cask "sbottui" do
  name "sbottui"
  desc ""
  homepage ""
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sbottui"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_darwin_amd64.tar.gz"
      sha256 "ed25b6c61afe014c3845eaa4090c2ce3c1c31cf447665701e2cf0f98d69935b5"
    end
    on_arm do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_darwin_arm64.tar.gz"
      sha256 "7dc9e0a7738c9462801ab05bb5ebffe3844e3dcb2ad9437dc844cc6a5ac2bfc0"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_linux_amd64.tar.gz"
      sha256 "8f9041c7c916badc26701a9e290a415d04a2f6190e837b6ae6124d77655097d7"
    end
    on_arm do
      url "https://github.com/yteraoka/sbottui/releases/download/v#{version}/sbottui_#{version}_linux_arm64.tar.gz"
      sha256 "c71ccb1d2c5929f9ac22c653026ac1405bf5348cd7d2e0f7de9c020569fbff8c"
    end
  end

  # No zap stanza required
end
