# This file was generated by GoReleaser. DO NOT EDIT.
cask "sbot" do
  name "sbot"
  desc ""
  homepage ""
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sbot"

  on_macos do
    on_intel do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_darwin_amd64.tar.gz"
      sha256 "0d901d69bb1c1f8922f565501fd0b0ef9921c4176b1f4697cf8fc4afd078b491"
    end
    on_arm do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_darwin_arm64.tar.gz"
      sha256 "0b798099d391f07b6454b00c6cb2e4014ac201eed45928e6516c7234b8190c86"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_linux_amd64.tar.gz"
      sha256 "170ecf01b9b258c0704e9c7a60d8c492a5704e6479605d61deb81bb4f7d98c40"
    end
    on_arm do
      url "https://github.com/yteraoka/sbot/releases/download/v#{version}/sbot_#{version}_linux_arm64.tar.gz"
      sha256 "b20d9548a3e8b845c98036cb2f1adf6c2ec9345b71d3ba9ccf946b6041664888"
    end
  end

  # No zap stanza required
end
